apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/mcastellini/argotest
      targetRevision: HEAD
      ref: repo
    - chart: crossplane
      repoURL: https://charts.crossplane.io/stable
      targetRevision: 1.11.*
      helm:
        valueFiles:
          - $repo/gitops/crossplane/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
