apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capsule
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/mcastellini/argotest
      targetRevision: HEAD
      ref: repo
    - chart: capsule
      repoURL: https://clastix.github.io/charts
      targetRevision: 0.4.*
      helm:
        values: |
          manager:
            options:
              capsuleUserGroups:
                - system:serviceaccounts:argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: capsule-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
